// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package user

import (
	"github.com/google/wire"
	"go.mongodb.org/mongo-driver/v2/mongo"
	"server/internal/user/internal/repo"
	"server/internal/user/internal/repo/dao"
	"server/internal/user/internal/service"
	"server/internal/user/internal/web"
	"server/internal/user_detail"
)

// Injectors from wire.go:

func InitUserModule(database *mongo.Database, userDetailModule *user_detail.Module) *Module {
	userDao := dao.NewUserDao(database)
	userRepo := repo.NewUserRepo(userDao)
	userService := service.NewUserService(userRepo)
	iUserDetailService := userDetailModule.Svc
	userHandler := web.NewUserHandler(userService, iUserDetailService)
	module := &Module{
		Hdl: userHandler,
		Svc: userService,
	}
	return module
}

// wire.go:

var userProvider = wire.NewSet(web.NewUserHandler, service.NewUserService, repo.NewUserRepo, dao.NewUserDao, wire.Bind(new(service.IUserService), new(*service.UserService)), wire.Bind(new(repo.IUserRepo), new(*repo.UserRepo)), wire.Bind(new(dao.IUserDao), new(*dao.UserDao)))
